controller_manager: # Has to be named "controller_manager" in ROS 2
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        #publish_rate: 100
        #Joint state "controller" is deprecated in ROS2 now in order to
        #differentiate between true controllers and simple data broadcasters.
        #The joint state broadcaster publishes the current states from ros2_control system.

    joints_effort_controller:
      type: effort_controllers/JointGroupEffortController
      #The joint effort controller commands a group of joints through the effort interface

    joints_position_controller:
      type: position_controllers/JointGroupPositionController 
      #The joint position controller commands a group of joints through position

joints_effort_controller:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
      - Joint7
      - Joint8
      - Joint9

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity
      - effort

joints_position_controller:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
      - Joint7
      - Joint8
      - Joint9

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
      - effort
    
    interface_name: position
