controller_manager: # This is the namespace? of the controller yaml file
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        #publish_rate: 100
        #Joint state "controller" is deprecated in ROS2 now in order to
        #differentiate between true controllers and simple data broadcasters.
        #The joint state broadcaster publishes the current states from ros2_control system.

    joints_effort_controller:
      type: effort_controllers/JointGroupEffortController
      #The joint effort controller commands a group of joints through the effort interface

joints_effort_controller:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
      - Joint7
      - Joint8
      - Joint9

    command_interfaces:
      - effort
      # - Joint1/effort
      # - Joint2/effort
      # - Joint3/effort
      # - Joint4/effort
      # - Joint5/effort
      # - Joint6/effort
      # - Joint7/effort
      # - Joint8/effort
      # - Joint9/effort
    

    state_interfaces:
      - position
      - velocity
      - effort
